microsoft/terraform-provider-fabric

.changes/unreleased/fixed-20240925-204940.yaml, docs/data-sources/workspace.md, internal/services/workspace/data_workspace.go, internal/testhelp/wellknown.go
close #15
This pull request addresses a schema issue in the `fabric_workspace` data-source and includes related documentation and code updates. The most important changes include fixing the schema, updating the documentation, and modifying the relevant code to reflect the schema change.
Documentation Update:
* [`docs/data-sources/workspace.md`](diffhunk://#diff-7cd9d7c89e4d61074ba868cdb987ff36a2cd7b06c205e0926cb33a0e37a4c586L70-R71): Updated the `enabled` attribute to `type` in the workspace identity documentation.
Bug Fix:
* [`internal/services/workspace/data_workspace.go`](diffhunk://#diff-56f9c23c9a9645da1fae3a5fb8a2019a63fe3ccc69d44b973c1cc4e733df273bL88-R89): Modified the schema attribute from `enabled` (bool) to `type` (string) in the `Schema` function.
Bug Fix:
* …
=> fix(ds-workspace): invalid schema for the workspace identity

.changes/unreleased/added-20240930-235244.yaml, .goreleaser.yml
This pull request includes changes to add support for additional binaries in the build artifacts. The most important changes involve updates to the build configuration to include FreeBSD and 386 architectures.
Build configuration updates:
* [`.goreleaser.yml`](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R26-R37): Updated `goos` to include FreeBSD and `goarch` to include 386. Also modified the `ignore` section to exclude 386 architecture for Darwin.
=> feat(build): add additional binaries

Taskfile.yml, docs/guides/troubleshooting.md, templates/guides/troubleshooting.md.tmpl
This pull request includes updates to the documentation to correct file references for the `fabric_workspace` resource. The changes ensure that the links point to the correct `.md` file.
* [`docs/guides/troubleshooting.md`](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L38-R38): Updated the reference to `fabric_workspace` resource to point to `workspace.md` instead of `workspace`. [[1]](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L38-R38) [[2]](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L47-R47)
* [`templates/guides/troubleshooting.md.tmpl`](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L38-R38): Updated the reference to …
=> docs: fix broken links in troubleshooting guide

.devcontainer/devcontainer.json, go.mod
This pull request includes updates to the `.devcontainer/devcontainer.json` and `go.mod` files to upgrade the versions of Go and Terraform used in the project.
Version upgrades:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L18-R18): Updated the Go version from `1.23.1` to `1.23.2`.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L39-R39): Updated the Terraform version from `1.9.6` to `1.9.7`.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3-R3): Updated the Go version from `1.23.1` to `1.23.2`.
=> build(deps): bump go and terraform

.changes/unreleased/fixed-20241003-000007.yaml, internal/services/workspace/resource_workspace.go
This pull request introduces a checkpoint mechanism for saving intermediary states in the `fabric_workspace` resource, which helps in improving the reliability of state management during create and update operations.
* `internal/services/workspace/resource_workspace.go`:
* `func (r *resourceWorkspace) Create(ctx context.Context, req resource.CreateReque)`: Added intermediary state save checkpoints after creating the resource and before setting the final state. 
* `func (r *resourceWorkspace) Update(ctx context.Context, req resource.UpdateReque)`: Introduced an `intermediary` variable to hold the state at different stages of the update process, and added checkpoints to save this intermediary state.
=> fix(rs-workspace): add intermediary state checkpoints

.changes/unreleased/changed-20241003-184918.yaml, docs/guides/auth_app_reg_spn.md, docs/guides/auth_msi.md, docs/guides/auth_spn_oidc.md, examples/guides/auth_app_reg_spn/app_reg.ps1, examples/guides/auth_app_reg_spn/app_reg.sh, examples/guides/auth_msi/azurevm_sami.ps1, examples/guides/auth_msi/azurevm_sami.sh, examples/guides/auth_msi/azurevm_uami.ps1, examples/guides/auth_msi/azurevm_uami.sh, examples/guides/auth_spn_oidc/credential.json, templates/guides/auth_spn_oidc.md.tmpl
This pull request includes updates to several documentation and example script files to enhance clarity and functionality when working with Azure CLI and Microsoft Fabric. The most important changes include the addition of bash shebangs, setting input variables, and updating commands to improve usability and consistency.
* [`docs/guides/auth_app_reg_spn.md`](diffhunk://#diff-b04a7fdf579ebd0aa397fa5dc97d288888a290e5da9aeb446e7cd1168d3abeccL28-R40): Added bash shebang, set input variables, and updated Azure CLI commands for creating an App Registration with Service Principal. [[1]](diffhunk://#diff-b04a7fdf579ebd0aa397fa5dc97d288888a290e5da9aeb446e7cd1168d3abeccL28-R40) [[2]](diffhunk://#diff-b04a7fdf579ebd0aa397fa5dc97d288888a290e5da9aeb446e7cd1168d3abeccR61-R76)
* …
=> docs: update bash scripts to use az fabric extension

.github/workflows/test.yml, README.md
This pull request includes updates to the GitHub Actions workflow and the `README.md` file to enhance project documentation and workflow capabilities.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3): Added a badge for the test workflow to provide a quick visual indication of the test status.
Workflow enhancements:
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R17): Added the `workflow_dispatch` trigger to allow manual triggering of the workflow.
=> ci(test): add manual trigger option to test workflow

.changes/unreleased/fixed-20241011-205500.yaml, internal/services/lakehouse/models_resource_lakehouse.go, internal/services/lakehouse/resource_lakehouse_test.go
close #41
This pull request addresses a bug fix in the `fabric_lakehouse` resource creation and enhances the test coverage for different configurations. The key changes include fixing the resource creation logic when schemas are disabled and expanding the test cases to cover more scenarios.
* [`.changes/unreleased/fixed-20241011-205500.yaml`](diffhunk://#diff-f0c6196f7cc4d5f0d02c62d97da4755c989a3f0741826bc18bd99d816e0a3931R1-R5): Added a new entry to document the fix for the `fabric_lakehouse` resource creation failure when `configuration.enable_schemas` is set to `false`.
* [`internal/services/lakehouse/models_resource_lakehouse.go`](diffhunk://#diff-21525041e68a2b1aa2a83bd03af29dbd976f98b5893b2da2edff25b312968068L38-R38): Corrected the condition to check if `configuration.EnableSchemas` …
=> fix(rs-lakehouse): creation failing when enable_schemas is false

.github/workflows/test.yml, Taskfile.yml
- Sometimes, tests in the pipeline may take slightly longer that 15 minutes to complete
- If that happens, the pipeline will fail due to the timeout
- This PR extends the timeout for tests from 15 to 30 minutes to prevent pipeline failures
- 
- Extend timeout for tests from 15 to 30 minutes
=> test: extend timeout for tests from 15 to 30 minutes

.changes/unreleased/added-20241011-163624.yaml, .changes/unreleased/changed-20241011-163751.yaml, docs/data-sources/capacities.md, docs/data-sources/capacity.md, docs/data-sources/workspace.md, docs/resources/workspace.md, internal/services/capacity/data_capacities.go, internal/services/capacity/data_capacity.go, internal/services/workspace/data_workspace.go, internal/services/workspace/models.go, internal/services/workspace/resource_workspace.go, internal/testhelp/fakes/fabric_workspace.go
This pull request includes several updates to the documentation and internal codebase to provide more detailed information about capacity and workspace attributes, including possible values for various properties.
* Added possible values for `region` and `state` attributes in `docs/data-sources/capacities.md`.
* Added possible values for `region` and `state` attributes in `docs/data-sources/capacity.md`.
* Added possible values for `capacity_assignment_progress` and `capacity_region` attributes, and included a nested schema for `onelake_endpoints` in `docs/data-sources/workspace.md`. [[1]](diffhunk://#diff-7cd9d7c89e4d61074ba868cdb987ff36a2cd7b06c205e0926cb33a0e37a4c586L49-R54) [[2]](diffhunk://#diff-7cd9d7c89e4d61074ba868cdb987ff36a2cd7b06c205e0926cb33a0e37a4c586R74-R82)
* Added possible …
=> feat(workspace-capacity): add additional properties for region and 1lake endpoints

.golangci.yml, internal/functions/content_decode.go
This pull request includes several changes to the `.golangci.yml` configuration file and a modification to the `functionContentDecode` struct methods in `internal/functions/content_decode.go` to fix linting issues.
* [`.golangci.yml`](diffhunk://#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9L52-L55): Removed deprecated linters `gomnd` and `execinquery` from the `disable` list.
* [`.golangci.yml`](diffhunk://#diff-6179837f7df53a6f05c522b6b7bb566d484d5465d9894fb04910dd08bb40dcc9R105-R106): Added `max-public-structs` to the `linters-settings` section and disabled it.
* [`internal/functions/content_decode.go`](diffhunk://#diff-b2e4153446202790f72e0a5ae2d1c5c71195dd56d78c927733a968f565730f46L28-R32): Changed the receiver type of methods `Metadata` and `Definition` from …
=> fix(lint): go code linting

.changes/unreleased/fixed-20241121-214245.yaml, .goreleaser.yml, Taskfile.yml, main.go
- The `main.version` value is not being properly updated during the build and release process, leaving the default `dev` value unmodified
- Fixes #102 
- Now, the package name is removed from the flags used to set main.version during the release process. It only passes `main.version=<version>`
- If the provider binary is executed as a standalone binary, it will print the version and exit.
=> fix(ci): Remove the package name from the flags used to set main.version during the release process

internal/services/eventhouse/data_eventhouses_test.go, internal/services/semanticmodel/data_semantic_models_test.go
This pull request includes changes to remove conditional test skips in the `internal/services/eventhouse/data_eventhouses_test.go` and `internal/services/semanticmodel/data_semantic_models_test.go` files. The most important changes include removing the `testhelp.ShouldSkipTest` checks from the affected test functions.
* [`internal/services/eventhouse/data_eventhouses_test.go`](diffhunk://#diff-d9e4745346ceb6b5e1e0db0b1d6ca4bf65525ef2b056c76203700fd592e81c4cL78-L81): Removed the conditional skip check for SPN support in the `TestAcc_EventhousesDataSource` test function.
* [`internal/services/semanticmodel/data_semantic_models_test.go`](diffhunk://#diff-018ed8f2e732aaa3c238a1294df9d5d1c946cb03752d7af1b23d5af37da9c1adL78-L81): Removed the conditional skip check for SPN support in the …
=> test: remove SPN skip from eventhouses and semantic models tests

.changes/unreleased/fixed-20241125-090146.yaml, docs/data-sources/workspace_git.md, docs/resources/workspace_git.md, internal/services/workspace/data_workspace_git.go, internal/services/workspace/resource_workspace_git.go
close #108 
This pull request includes changes to remove references to GitHub support from the documentation and codebase, as it is not yet supported by the provider. The most important changes include updates to documentation files and schema definitions to reflect this removal.
* [`docs/data-sources/workspace_git.md`](diffhunk://#diff-ba680457622059b12ddb69bf491cf0ee36bfe48dc00990359cf69e521cde8668L54-R54): Removed `GitHub` from the possible values of `git_provider_type`.
* [`docs/resources/workspace_git.md`](diffhunk://#diff-f260a1fbe1e8258810be5d024e7e841b9c6ff1392c1dd4ddb68eba2b916ffaabL63-R63): Removed `GitHub` from the accepted values of `git_provider_type`.
Code updates:
* [`internal/services/workspace/data_workspace_git.go`](diffhunk://#diff-07308d0bd0e45b85 …
=> fix(ws-git): remove github from docs

.changes/unreleased/fixed-20241119-215139.yaml, .changes/unreleased/fixed-20241122-130758.yaml, internal/common/errors.go, internal/services/domain/resource_domain_role_assignments_test.go, internal/services/kqldatabase/resource_kql_database_test.go, internal/services/workspace/resource_workspace.go, internal/services/workspace/resource_workspace_git_test.go, internal/services/workspace/resource_workspace_test.go
fix #93
This pull request includes changes to the `Create` method in the `resourceWorkspace` struct to improve state management and ensure that the state is properly updated. The most important changes include initializing the `state` variable, setting `state.Timeouts` and `state.ID`, and updating the `get` and `Set` methods to use `state` instead of `plan`.
State management improvements:
* [`internal/services/workspace/resource_workspace.go`](diffhunk://#diff-87c99c17b488a2914da585da7b4f1eacb8b55b7439c0f8a2cff0c51753da2608L207-R207): Initialized the `state` variable alongside `plan`.
* [`internal/services/workspace/resource_workspace.go`](diffhunk://#diff-87c99c17b488a2914da585da7b4f1eacb8b55b7439c0f8a2cff0c51753da2608R221-R222): Set `state.Timeouts` to `plan.Timeouts`.
* …
=> fix(workspace): update resource creation to handle state correctly for identity

.devcontainer/devcontainer.json, .github/workflows/test.yml
This pull request includes updates to the Terraform and Tofu versions used in the development container and GitHub Actions workflows, as well as some environment configuration changes for testing.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L39-R45): Updated Terraform version from `1.9.8` to `1.10.0` and Tofu version from `1.8.5` to `1.8.6`.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L337-R344): Added support for Terraform version `1.10` and excluded Tofu version `1.10` from specific tests.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R423): Added `TF_LOG: DEBUG` to the …
=> build(deps): update terraform and tofu

.devcontainer/devcontainer.json, go.mod
This pull request includes updates to the Go version used in the project.
* Updated the Go version in `.devcontainer/devcontainer.json` from `1.23.3` to `1.23.4`.
* Updated the Go version in `go.mod` from `1.23.3` to `1.23.4`.
=> build(deps): bump Go version from 1.23.3 to 1.23.4

.changie.yaml, docs/guides/getting_started.md, templates/guides/getting_started.md.tmpl
This pull request includes updates to the `getting_started.md` guide and its template to improve clarity and consistency, as well as a minor change to the `.changie.yaml` configuration file.
Improvements to documentation:
* `docs/guides/getting_started.md` and `templates/guides/getting_started.md.tmpl`: Corrected terminology to use "Notebook" and "Lakehouse" consistently with proper capitalization. [[1]](diffhunk://#diff-475d3e393e0447deccac73a32a7ec81e02abb8eb3d38a9ddf6ae14ff5f1e71c7L10-R16) [[2]](diffhunk://#diff-475d3e393e0447deccac73a32a7ec81e02abb8eb3d38a9ddf6ae14ff5f1e71c7L31-R37) [[3]](diffhunk://#diff-475d3e393e0447deccac73a32a7ec81e02abb8eb3d38a9ddf6ae14ff5f1e71c7L58-R60) [[4]](diffhunk://#diff-475d3e393e0447deccac73a32a7ec81e02abb8eb3d38a9ddf6ae14ff5f1e71c7L88-R90) …
=> docs(guides): improve formatting in getting started

internal/provider/provider.go
This pull request modifies the `internal/provider/provider.go` file to update the application-specific identification string used in telemetry.
* [`internal/provider/provider.go`](diffhunk://#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22L117-R117): Changed the `ApplicationID` from "tfprov-fabric/" to "tffab/" to shorten and simplify the identification string used in telemetry.
=> fix(provider): update appid format in telemetry

internal/pkg/fabricitem/data_item.go, internal/pkg/fabricitem/data_item_definition.go, internal/pkg/fabricitem/data_schema.go, internal/pkg/fabricitem/resource_item.go, internal/pkg/fabricitem/resource_item_definition.go, internal/pkg/fabricitem/resource_schema.go, internal/services/environment/data_environment.go, internal/services/eventhouse/data_eventhouse.go, internal/services/kqldatabase/data_kql_database.go, internal/services/lakehouse/data_lakehouse.go, internal/services/lakehouse/resource_lakehouse.go
This pull request includes several changes to the `internal/pkg/fabricitem` package to refactor the schema generation functions for better consistency and maintainability. The changes involve modifying the way schema attributes are passed and organized and removing redundant code.
* [`internal/pkg/fabricitem/data_item.go`](diffhunk://#diff-78ca03c11129aabf8542b34344736e45023c0524c94f46188e31b993815534acL48-R48): Updated the `Schema` method in `DataSourceFabricItem` to pass the entire `DataSourceFabricItem` struct instead of individual attributes.
* [`internal/pkg/fabricitem/data_item_definition.go`](diffhunk://#diff-380ac3fbb146117b87b0fc813d1167045947ed19b7d8098fdcbaae5ef28db6aeL52-R52): Updated the `Schema` method in `DataSourceFabricItemDefinition` to pass the entire …
=> refactor(fabitem): simplify schema and remove redundant code

internal/services/domain/resource_domain_role_assignments.go, internal/services/domain/resource_domain_workspace_assignments.go, internal/services/environment/data_environment.go, internal/services/environment/models.go, internal/services/warehouse/data_warehouse.go, internal/services/warehouse/models.go, internal/services/warehouse/resource_warehouse.go, internal/services/workspace/data_workspace.go, internal/services/workspace/models.go, internal/services/workspace/models_data_workspace_role_assignments.go, internal/services/workspace/resource_workspace.go
This pull request focuses on enhancing error handling by ensuring that diagnostic information is properly propagated and checked across various functions. The changes span multiple files and functions.
These changes collectively improve the robustness of the code by ensuring that errors are properly handled, and diagnostic information is propagated throughout the system.
* [`internal/services/domain/resource_domain_role_assignments.go`](diffhunk://#diff-b1d01fb021b90119118f9a17c373d190c58abbf643d178c48c2ad5f82228d701L317-R319): Updated the `Delete` function to append diagnostics and check for errors after setting the request.
* [`internal/services/domain/resource_domain_workspace_assignments.go`](diffhunk://#diff-24bfcf1e3d5ab7ecf9eedac02be1ab93ec11f69adad3a76a76475adba4733b13L290-R292): …
=> fix: add missing diags

.github/workflows/test.yml, Taskfile.yml
This pull request updates the `.github/workflows/test.yml` file to change the output variable used for conditional checks from `changes` to `src`.
`changes` keywork is used by action itself and current filter was not working properly - it always run.
bonus: optimized taskfile and test execution
Changes to conditional checks in `.github/workflows/test.yml`
=> fix(ci): change to src, changes was reserved keyword by action

.github/dependabot.yml
This pull request includes updates to the `.github/dependabot.yml` file to add labels for dependencies across different package ecosystems.
Label additions:
* Added labels `deps/github-actions` and `dependencies` for the GitHub Actions package ecosystem.
* Added labels `deps/devcontainer` and `dependencies` for the devcontainers package ecosystem.
* Added labels `deps/go` and `dependencies` for the Go modules package ecosystem.
=> ci(dependabot): add labels

.devcontainer/devcontainer.json, .github/workflows/test.yml, DEVELOPER.md, tools/scripts/Set-WellKnown.ps1
This pull request includes updates to the `.devcontainer/devcontainer.json` and significant modifications to the `.github/workflows/test.yml` file to streamline the CI/CD process and ensure proper environment setup.
* Updated the Terraform version from `1.10.2` to `1.10.3` to ensure the latest features and fixes are included.
* Added a command to change ownership of the PowerShell directory to the `vscode` user after the container is created.
* Changed the path for `pwsh` and set `powershell.powerShellDefaultVersion` to `pwsh`.
* Added the `ms-azuretools.vscode-azure-github-copilot` extension to the list of recommended extensions.
* Reorganized jobs to ensure that the `changes` job runs first and subsequent jobs depend on its output, improving efficiency by only running tests if there are …
=> feat: improve devenv setup and ci for test

.changes/unreleased/fixed-20250108-115142.yaml, docs/resources/domain_workspace_assignments.md, internal/services/domain/models_resource_domain_workspace_assignments.go, internal/services/domain/resource_domain_workspace_assignments.go
- Currently `domain_workspace_assignments` resource enforce assignments based only on TF configuration. It means if someone adds more resources manually on the Fabric side, the next run of TF will remove it. Expected behavior: Resource must only manage TF provided configuration.
This fix is related (not directly) to #174 and potentially to #183
=> fix(domain): workspace assignments should only care about managed resources

.devcontainer/devcontainer.json, DEVELOPER.md, go.mod
This pull request includes updates to the versions of Go and Terraform across various configuration and documentation files to ensure consistency and compatibility.
Version updates:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L18-R18): Updated the Go feature version from `1.23.5` to `1.23.6`.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L39-R39): Updated the Terraform feature version from `1.10.4` to `1.10.5`.
* [`DEVELOPER.md`](diffhunk://#diff-35ea617bfbf0780bfbc554348314c5b11ba478a4d98fd92d33d45cdd54bf326aL111-R116): Updated the required versions of Go and Terraform to `1.23.6` and `1.10.5` respectively, and adjusted the version manager …
=> build(deps): update go to 1.23.6 and terraform to 1.10.5

.changes/unreleased/added-20250206-133034.yaml, .vscode/launch.json, .vscode/settings.json, docs/guides/troubleshooting.md, go.mod, internal/provider/client/logging.go, internal/provider/provider.go, templates/guides/troubleshooting.md
This pull request introduces logging enhancements for API/SDK interactions and updates related documentation and configuration files. The key changes include enabling detailed logging for API calls and updating the troubleshooting guide.
* Added a new logging subsystem for the Microsoft Fabric SDK to capture detailed API interactions. (`internal/provider/client/logging.go`)
* Integrated the new logging subsystem into the provider client creation process. (`internal/provider/provider.go`)
* Updated the troubleshooting guide to include instructions for enabling low-level logging for API calls. (`docs/guides/troubleshooting.md`, `templates/guides/troubleshooting.md`)
=> feat(logging): enable api/sdk interaction logging

internal/provider/client/logging.go
This pull request includes a change to the `internal/provider/client/logging.go` file to improve the logging configuration for the Fabric SDK. The most important change is the modification of the logic that enables Azure SDK logging based on the target logging level.
Logging configuration improvement:
* [`internal/provider/client/logging.go`](diffhunk://#diff-b0adf1bef9698ebb0eabbadf00f5b31f6b21717837649818498f1c23a1968f8aL26-R29): Adjusted the logic to enable Azure SDK logging only if the target logging level is not set to "off". This ensures that logging is properly configured based on the specified level.
=> fix(logging): enable sdk logging only when target level is not set to off

.changes/unreleased/fixed-20250206-214937.yaml, docs/resources/spark_custom_pool.md, internal/services/spark/base_test.go, internal/services/spark/data_spark_custom_pool_test.go, internal/services/spark/resource_spark_custom_pool.go, internal/services/spark/resource_spark_custom_pool_test.go
fix #239
This pull request includes changes to address the inconsistent results for dynamic executor allocation when the `enabled` attribute is set to false and updates the documentation and schema accordingly.
* `internal/services/spark/resource_spark_custom_pool.go`: 
* Added new imports for `attr`, `types`, and `superint32validator` packages.
* Updated the schema for `min_executors` and `max_executors` attributes to be `Computed` and `Optional`, and added validators to handle the `dynamic_executor_allocation` `enabled` attribute.
* [`docs/resources/spark_custom_pool.md`](diffhunk://#diff-e2c5956959615a4e86cc330845da0052ce2316efdf948d7bea320eb2365fbab3R81-R83): Added an `Optional` section to the documentation for `max_executors` and `min_executors` attributes.
=> fix(rs-spark_custom_pool): inconsistent result for dynamic_executor_allocation

.changes/unreleased/fixed-20250212-122940.yaml, docs/data-sources/semantic_model.md, docs/resources/semantic_model.md, internal/services/semanticmodel/base.go
fix #247
Add support for missing `definition/expressions.tmdl` and `definition/relationships.tmdl` paths in the Semantic Model TMDL format.
=> fix(semantic-model-tmdl): add missing paths

.devcontainer/devcontainer.json, .github/workflows/test.yml, DEVELOPER.md
This pull request includes updates to the Terraform version used in various configuration files and documentation. 
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L39-R39): Updated the Terraform version from `1.10.5` to `1.11.0`.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L321-R334): Added Terraform version `1.11` to the matrix and excluded it from specific tests.
* [`DEVELOPER.md`](diffhunk://#diff-35ea617bfbf0780bfbc554348314c5b11ba478a4d98fd92d33d45cdd54bf326aL114-R116): Updated the recommended Terraform version from `1.10.5` to `1.11.0` in the development setup instructions.
=> ci(deps): update terraform to 1.11.0

.devcontainer/devcontainer.json, DEVELOPER.md, go.mod
This pull request includes updates to the development environment configurations and documentation to ensure compatibility with the latest versions of Go and Terraform.
Updates to development environment:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L12-R18): Updated the `fish` feature to version 2, the `go` feature to version 1.24.1, and the `terraform` feature to version 1.11.1. [[1]](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L12-R18) [[2]](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L39-R39)
* [`DEVELOPER.md`](diffhunk://#diff-35ea617bfbf0780bfbc554348314c5b11ba478a4d98fd92d33d45cdd54bf326aL111-R116): Updated the …
=> build(deps): update go, tf and devcontainer

tools/scripts/Set-WellKnown.ps1
This pull request includes a small change to the `tools/scripts/Set-WellKnown.ps1` file. The change modifies the `Install-Module` command within the `Install-ModuleIfNotInstalled` function to include additional parameters for skipping publisher checks, accepting licenses, and disabling confirmation prompts.
* [`tools/scripts/Set-WellKnown.ps1`](diffhunk://#diff-cd040f9d9e24e510ff0d29df8f78489fbd234634352aa2fbbf2b99a9a52fcc4cL45-R45): Modified the `Install-Module` command to include `-Confirm:$false`, `-SkipPublisherCheck`, and `-AcceptLicense` parameters.
=> fix(wellknown): enhance Install-Module command with additional params

.changes/unreleased/changed-20250306-194949.yaml, docs/data-sources/data_pipeline.md, docs/data-sources/data_pipelines.md, docs/resources/data_pipeline.md, internal/services/datapipeline/base.go, internal/services/datapipeline/data_data_pipeline_test.go, internal/services/datapipeline/resource_data_pipeline_test.go
This pull request includes changes to support Service Principal (SPN) authentication for Data Pipeline resources and data sources. The changes span across documentation updates and code modifications to reflect this new support.
=> feat(data_pipeline): enable spn support

.changes/unreleased/changed-20250304-204546.yaml, docs/resources/kql_database.md, examples/resources/fabric_kql_database/outputs.tf, examples/resources/fabric_kql_database/resource.tf, internal/pkg/fabricitem/resource_item.go, internal/pkg/fabricitem/resource_item_config_definition_properties.go, internal/pkg/fabricitem/resource_item_config_properties.go, internal/pkg/fabricitem/resource_item_definition.go, internal/pkg/fabricitem/resource_item_definition_properties.go, internal/pkg/fabricitem/resource_item_properties.go, internal/services/domain/resource_domain.go, internal/services/domain/resource_domain_role_assignments.go, internal/services/domain/resource_domain_workspace_assignments.go, internal/services/kqldatabase/models_resource_kql_database.go, internal/services/kqldatabase/resource_kql_database.go, internal/services/kqldatabase/schema_resource_kql_database.go, internal/services/spark/resource_spark_custom_pool.go, internal/services/spark/resource_spark_environment_settings.go, internal/services/spark/resource_spark_workspace_settings.go, internal/services/workspace/resource_workspace.go, internal/services/workspace/resource_workspace_git.go, internal/services/workspace/resource_workspace_role_assignment.go
https://developer.hashicorp.com/terraform/plugin/framework/resources/write-only-arguments
https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only
=> feat(kql_database): deprecate token and add token_wo

.changes/unreleased/fixed-20250313-090918.yaml, docs/resources/data_pipeline.md, examples/resources/fabric_data_pipeline/resource.tf
This pull request includes changes to add a new `format` attribute to various `fabric_data_pipeline` resources in both documentation and example files. The most important changes are as follows:
* [`docs/resources/data_pipeline.md`](diffhunk://#diff-5c0014d01c92e5f78fb4d1486a8d97af0281e84589e065fd9d3b8bd56bda02a4R36): Added the `format` attribute with the value "Default" to the `fabric_data_pipeline` resource examples. [[1]](diffhunk://#diff-5c0014d01c92e5f78fb4d1486a8d97af0281e84589e065fd9d3b8bd56bda02a4R36) [[2]](diffhunk://#diff-5c0014d01c92e5f78fb4d1486a8d97af0281e84589e065fd9d3b8bd56bda02a4R53)
Example updates:
* [`examples/resources/fabric_data_pipeline/resource.tf`](diffhunk://#diff-65be83977c8ef370144f56df858fd47cf90090c74ba7c1feab0aadfd7743e41cR12): Added …
=> fix(docs): add default format to data pipeline resources examples

.vscode/launch.json, .vscode/settings.json, internal/provider/provider.go, internal/services/spark/resource_spark_environment_settings.go, internal/services/spark/resource_spark_workspace_settings.go
This pull request includes changes to enhance logging capabilities for the Fabric SDK Go. The most important changes include updating environment configurations and modifying the client creation function to include logging options.
Enhancements to logging capabilities:
* [`.vscode/launch.json`](diffhunk://#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945L12-R13): Added `FABRIC_SDK_GO_LOGGING_INCLUDE_BODY` environment variable to include request/response bodies in logs.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L66-R67): Added `FABRIC_SDK_GO_LOGGING_INCLUDE_BODY` environment variable to include request/response bodies in logs.
* [`internal/provider/provider.go`](diffhunk://#diff-58d6a027753b50994deb7e11e …
=> feat(logging): add sdk log options

.changie.yaml, .devcontainer/features/tfprovider-local-dev/install.sh, .gitattributes, .github/dependabot.yml, .vscode/settings.json, terraform-registry-manifest.json
This pull request includes several changes to configuration files to enhance documentation, update dependencies, and adjust settings for development tools. The most important changes include adding a new documentation label, modifying line ending settings, and updating dependabot configurations.
Configuration updates:
* [`.changie.yaml`](diffhunk://#diff-9f1c8d07b49e66598bb525c145a5d7524fef447d6993b72ccb378e70ebf922f3R33-R35): Added a new label for documentation changes to the `kinds` section.
* [`.gitattributes`](diffhunk://#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eL1-R2): Adjusted line ending settings to ensure consistent handling of line endings across different operating systems.
Dependency management:
* …
=> chore: repo hygiene, devex enhancement

examples/resources/fabric_activator/outputs.tf, examples/resources/fabric_data_pipeline/outputs.tf, examples/resources/fabric_domain/outputs.tf, examples/resources/fabric_domain_role_assignments/outputs.tf, examples/resources/fabric_domain_workspace_assignments/outputs.tf, examples/resources/fabric_environment/outputs.tf, examples/resources/fabric_eventhouse/outputs.tf, examples/resources/fabric_eventstream/outputs.tf, examples/resources/fabric_gateway/outputs.tf, examples/resources/fabric_gateway_role_assignment/outputs.tf, examples/resources/fabric_graphql_api/outputs.tf, examples/resources/fabric_kql_dashboard/outputs.tf, examples/resources/fabric_kql_database/outputs.tf, examples/resources/fabric_kql_queryset/outputs.tf, examples/resources/fabric_lakehouse/outputs.tf, examples/resources/fabric_mirrored_database/outputs.tf, examples/resources/fabric_ml_experiment/outputs.tf, examples/resources/fabric_ml_model/outputs.tf, examples/resources/fabric_notebook/outputs.tf, examples/resources/fabric_report/outputs.tf, examples/resources/fabric_semantic_model/outputs.tf, examples/resources/fabric_spark_custom_pool/outputs.tf, examples/resources/fabric_spark_environment_settings/outputs.tf, examples/resources/fabric_spark_job_definition/outputs.tf, examples/resources/fabric_spark_workspace_settings/outputs.tf, examples/resources/fabric_sql_database/outputs.tf, examples/resources/fabric_warehouse/outputs.tf, examples/resources/fabric_workspace/outputs.tf, examples/resources/fabric_workspace_git/outputs.tf, examples/resources/fabric_workspace_role_assignment/outputs.tf
This pull request includes updates to several Terraform output files to simplify the resource references. The changes remove the `resource.` prefix from the values.
=> chore(examples): remove resource prefix

.vscode/launch.json, .vscode/settings.json, internal/provider/provider.go
Use env var instead of hard-coding
This pull request includes updates to the logging configuration and enhancements to the header validation process. The most important changes include adding a new environment variable for allowed headers, updating the logging configuration in the VSCode settings, and introducing header validation using regular expressions.
Logging configuration updates:
* [`.vscode/launch.json`](diffhunk://#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945L13-R14): Added the `FABRIC_SDK_GO_LOGGING_ALLOWED_HEADERS` environment variable to specify allowed headers for logging.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L67-R68): Added the `FABRIC_SDK_GO_LOGGING_ALLOWED_HEADERS` environment …
=> feat(logging): add support for custom allowed headers in sdk

.changes/unreleased/added-20250318-195402.yaml, .github/workflows/test.yml, docs/data-sources/spark_workspace_settings.md, docs/resources/spark_workspace_settings.md, internal/services/spark/data_spark_workspace_settings.go, internal/services/spark/models_spark_workspace_settings.go, internal/services/spark/resource_spark_workspace_settings.go, internal/services/spark/resource_spark_workspace_settings_test.go
This pull request introduces an option to manage the "default pool" using the pool ID in the `fabric_spark_workspace_settings` resource. The changes span documentation updates, schema modifications, and test enhancements.
=> feat(spark_workspace_settings): add option to manage default pool using id

.changes/unreleased/changed-20250330-073034.yaml, docs/data-sources/environment.md, docs/data-sources/environments.md, docs/data-sources/eventstream.md, docs/data-sources/eventstreams.md, docs/data-sources/graphql_api.md, docs/data-sources/graphql_apis.md, docs/data-sources/warehouse.md, docs/data-sources/warehouses.md, docs/resources/environment.md, docs/resources/eventstream.md, docs/resources/graphql_api.md, docs/resources/warehouse.md, internal/services/environment/base.go, internal/services/eventstream/base.go, internal/services/graphqlapi/base.go, internal/services/warehouse/base.go
This pull request includes several changes to the documentation and internal service configurations for various Fabric data sources and resources. The main focus is on updating the preview status of these data sources and resources.
* Set `IsPreview` to `true` for the Environment data-source. (`internal/services/environment/base.go`)
* Set `IsPreview` to `false` for the Eventstream data-source. (`internal/services/eventstream/base.go`)
* Set `IsPreview` to `false` for the GraphQL API data-source. (`internal/services/graphqlapi/base.go`)
* Set `IsPreview` to `false` for the Warehouse data-source. (`internal/services/warehouse/base.go`)
=> fix: update items' preview status 

.github/dependabot.yml
Configure dependabot to ignore version update for microsoft/fabric in examples directory
=> fix(dependabot): ignore microsoft/fabric package in examples

.changes/unreleased/fixed-20250409-105232.yaml, internal/pkg/utils/errors.go, internal/pkg/utils/errors_test.go
Fix #362 
- Fix nil pointer dereference in fabric error response when RawResponse is nil. 
- Today this could happen when provisioning a `fabric_lakehouse` or `fabric_mirrored_database` and the underlying sql endpoint provisioning fails.
=> fix(nil pointer): handle fabric error response when RawReponse is nil 

.changes/unreleased/added-20250423-104539.yaml, docs/index.md, internal/provider/client/user_agent.go, internal/provider/config/envvars.go, internal/provider/config/model.go, internal/provider/provider.go
This pull request introduces telemetry enhancements and user agent customization for the Microsoft Fabric Terraform provider. The key changes include adding support for custom `partner_id` and an option to disable the default Terraform Partner ID, implementing a user agent policy, and updating the provider's schema and configuration to support these features.
* Added new attributes to the provider schema: `partner_id` (a GUID/UUID for partner attribution) and `disable_terraform_partner_id` (to disable the default Terraform Partner ID). These attributes can also be sourced from environment variables. (`internal/provider/provider.go`, [internal/provider/provider.goR332-R342](diffhunk://#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22R332-R342))
* Updated `ProviderData` …
=> feat(telemetry): add partner_id and improve user-agent

.changes/unreleased/fixed-20250319-005743.yaml, .changes/unreleased/fixed-20250512-104313.yaml, docs/data-sources/eventstream.md, docs/resources/eventstream.md, internal/services/eventstream/base.go, internal/testhelp/fixtures/eventstream/eventstreamProperties.json
This pull request includes several changes to add support for the `eventstreamProperties.json` definition path in the `fabric_eventstream`. The most important changes include updates to documentation, internal service configurations, and test fixtures.
* [`docs/data-sources/eventstream.md`](diffhunk://#diff-75c8eb00096d1c6e0215a8e868338c5757a32fcdfb0091534390e47715c6bb03L85-R85): Updated the `definition` attribute description to include the `eventstreamProperties.json` path.
* [`docs/resources/eventstream.md`](diffhunk://#diff-05affd310bebf46df4092c5d429117834a686812778faba8f534d2d8aeaac76bL73-R73): Updated the `definition` attribute description to include the `eventstreamProperties.json` path.
Internal service configuration:
* …
=> fix(eventstream): missing eventstreamProperties.json definition path

.changes/unreleased/fixed-20250515-194639.yaml, internal/pkg/utils/errors.go
close #440
The panic was occurring because:
1. An `azidentity.AuthenticationFailedError` was being passed to `processAuthFailedError`
2. The `RawResponse` field in this error was nil
3. The code was trying to access `resp.Body` in `getErrFromResp` without checking if `resp` itself was nil
4. This resulted in a nil pointer dereference (trying to access the `Body` field of a nil pointer)
The fix adds appropriate nil checks to prevent this panic situation and provides default error messages when these fields are not available.
1. Modified `processAuthFailedError` to check if `errAuthFailed.RawResponse` is nil before passing it to `getErrFromResp`.
2. Modified `getErrFromResp` to check if the `resp` parameter itself is nil, not just if `resp.Body` is nil.
These changes should fix the nil …
=> fix(errors): handle nil in auth error

internal/services/eventstreamsourceconnection/ephemeral_evenstream_source_connection_test.go
Due to API throttling limitations to eventstream_source_connection and returned http status code is 400 instead of 429, the polling mechanism on the GO SDK is not applied, and the tests are throttled, and so all test checks in the PRs will fail on throttling and would require manual rerun.
Skipping the ephemeral eventstream_source_connection acc test until issues is fixed on the API side.
PRs for new/enhanced resources or data sources are expected to meet the following criteria:
=> feat(fix): skip acc test for ephemeral eventstream_source_connection due to throttling issues

docs/ephemeral-resources/eventstream_source_connection.md, internal/pkg/fabricitem/helpers.go
The documentation automatically has the above note added
Therefore, this PR remove the redundant (and inaccurate) note that we added
=> fix(docs): remove redundant md description in ephemeral resource 
