docs/guides/troubleshooting.md, templates/guides/troubleshooting.md.tmpl
This pull request includes updates to the documentation files to improve clarity and accuracy. The most important changes are corrections to the phrasing and formatting of instructions related to Fabric Capacity and workspace management.
Documentation improvements:
* [`docs/guides/troubleshooting.md`](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L38-R52): Corrected phrasing to ensure clarity in instructions about assigning Fabric Capacity and checking user permissions.
* [`templates/guides/troubleshooting.md.tmpl`](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L38-R52): Updated template to match changes in the main troubleshooting guide, ensuring consistent phrasing and formatting.
=> docs: update faq in the troubleshooting guide

.changes/unreleased/changed-20241207-122252.yaml, Taskfile.yml, internal/pkg/utils/errors.go
This pull request includes changes to enhance error handling by improving the diagnostic error summary and detail messages by incorporating additional error details.
Enhancements to error handling:
* [`internal/pkg/utils/errors.go`](diffhunk://#diff-c6341322a4a197db867348773400c58b2986d9624c96f0ad9dd79b064cee7d20R126-R149): Updated the `GetDiagsFromError` function to extract and format additional error details from `errRespFabric.ErrorResponse.MoreDetails`, improving the diagnostic error summary and detail messages.
=> feat(errors): enhance diagnostics by including more details

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/ISSUE_TEMPLATE/tfprovider_data_source_request.yml, .github/ISSUE_TEMPLATE/tfprovider_docs_request.yml, .github/ISSUE_TEMPLATE/tfprovider_resource_request.yml
This pull request includes several updates to issue templates to improve clarity and consistency. The most important changes include updating the titles, adding project assignments, and enhancing the instructions for users.
Updates to issue templates:
* [`.github/ISSUE_TEMPLATE/bug_report.yml`](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL6-R14): Updated the title format, added project assignment, and enhanced the markdown instructions to include a troubleshooting guide link. [[1]](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efL6-R14) [[2]](diffhunk://#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR45)
* [`.github/ISSUE_TEMPLATE/feature_request.yml`](diffhunk://#diff-c6b098646bf32c644234bec14c267 …
=> feat(issues): add project ref to issue tmpls and enhance instructions

internal/pkg/utils/errors.go, internal/pkg/utils/errors_test.go
This pull request includes enhancements to the error handling and testing functionality in the `internal/pkg/utils` package. The most important changes include updates to the `GetDiagsFromError` function to handle new error types, improvements to the error message aggregation, and the addition of comprehensive unit tests for the `GetDiagsFromError` function.
* [`internal/pkg/utils/errors.go`](diffhunk://#diff-c6341322a4a197db867348773400c58b2986d9624c96f0ad9dd79b064cee7d20L108-R109): Updated `GetDiagsFromError` function to handle `azidentity.AuthenticationRequiredError` and renamed variables for clarity. Enhanced error message aggregation by using slices for error codes and messages. [[1]](diffhunk://#diff-c6341322a4a197db867348773400c58b2986d9624c96f0ad9dd79b064cee7d20L108-R109) …
=> fix(errors): enhance error handling for auth

.changes/unreleased/fixed-20250114-172547.yaml, docs/guides/auth_app_reg_user.md, templates/guides/auth_app_reg_user.md.tmpl
close #190
This pull request includes minor typo corrections to documentation files.
=> docs(app-req-user): fix typo

.changes/unreleased/changed-20250115-003905.yaml, docs/data-sources/warehouse.md, docs/data-sources/warehouses.md, docs/resources/warehouse.md, internal/services/warehouse/base.go, internal/services/warehouse/data_warehouse_test.go, internal/services/warehouse/data_warehouses_test.go, internal/services/warehouse/resource_warehouse_test.go
Enabled SPN support for Warehouse
=> feat(warehouse): enable spn support

.devcontainer/devcontainer.json, .github/workflows/test.yml
This pull request includes updates to the version of terraform and opentofu.
Version updates in `.devcontainer/devcontainer.json`:
* Updated the `terraform` feature from version `1.10.3` to `1.10.4`.
* Updated the `opentofu` feature from version `1.8.7` to `1.9.0`.
Workflow adjustments in `.github/workflows/test.yml`:
* Removed the exclusion of `tofu` version `1.9` under the `jobs:` section.
=> build(dev): update terraform and onboard opentofu 1.9.0

.changes/unreleased/added-20250125-122542.yaml, .changes/unreleased/added-20250125-122543.yaml, docs/data-sources/eventstream.md, docs/resources/eventstream.md, examples/data-sources/fabric_eventstream/data-source.tf, examples/resources/fabric_eventstream/resource.tf, internal/services/eventstream/base.go, internal/services/eventstream/base_test.go, internal/services/eventstream/data_eventstream.go, internal/services/eventstream/data_eventstream_test.go, internal/services/eventstream/data_eventstreams.go, internal/services/eventstream/resource_eventstream.go, internal/services/eventstream/resource_eventstream_test.go, internal/services/notebook/data_notebook_test.go, internal/testhelp/fixtures/eventstream/eventstream.json.tmpl
close #159
close #160
Add definition support to the Eventstream
=> feat(eventstream): add definition support

Taskfile.yml, docs/guides/troubleshooting.md, docs/index.md, templates/guides/troubleshooting.md, templates/index.md.tmpl
This pull request includes changes to improve Terraform execution parallelism and documentation updates. The most important changes include setting Terraform CLI arguments for parallelism, updating troubleshooting guides, and correcting a documentation typo.
Terraform execution improvements:
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR26-R28): Added `TF_CLI_ARGS_plan`, `TF_CLI_ARGS_apply`, and `TF_CLI_ARGS_destroy` to set parallelism to 3 for Terraform operations.
* [`docs/guides/troubleshooting.md`](diffhunk://#diff-05fa5078290d9319b91e520b8d624cd018e97d963be0d0e1cd22ca7e37e899e9L58-R59): Added a suggestion to change Terraform parallelism to a lower number than the default (10) to help with long-running …
=> docs: update troubleshooting guide and add parallelism settings

.changes/unreleased/added-20250125-102124.yaml, docs/data-sources/kql_database.md, docs/resources/kql_database.md, internal/services/kqldatabase/base.go, internal/services/kqldatabase/data_kql_database.go, internal/services/kqldatabase/data_kql_database_test.go, internal/services/kqldatabase/resource_kql_database.go, internal/services/kqldatabase/resource_kql_database_test.go
Add definition support to the KQL Database
=> feat(kql_database): add definition support

.golangci.yml, internal/auth/token_credential_test.go, internal/framework/customtypes/url_type_test.go, internal/framework/customtypes/url_value_test.go, internal/framework/customtypes/uuid_type_test.go, internal/framework/customtypes/uuid_value_test.go, internal/framework/typeutils/dynamic_json_test.go, internal/framework/validators/patterns_if_attribute_is_one_of_test.go, internal/pkg/transforms/payload.go, internal/pkg/utils/errors_test.go, internal/provider/provider.go, internal/provider/provider_test.go
This pull request includes several changes to the codebase, mainly focusing on linting and code cleanup by replacing the use of `context.Background()` with `t.Context()` in test files and modifying the `setConfig` and `mapConfig` methods to return the context.
=> chore: lint and code cleanup

.changes/unreleased/changed-20250305-154933.yaml, docs/data-sources/domain.md, docs/data-sources/domain_workspace_assignments.md, docs/data-sources/domains.md, docs/resources/domain.md, docs/resources/domain_role_assignments.md, docs/resources/domain_workspace_assignments.md, internal/services/domain/base.go, internal/services/domain/data_domain.go, internal/services/domain/data_domain_workspace_assignments.go, internal/services/domain/data_domains.go, internal/services/domain/resource_domain.go, internal/services/domain/resource_domain_role_assignments.go, internal/services/domain/resource_domain_role_assignments_test.go, internal/services/domain/resource_domain_test.go, internal/services/domain/resource_domain_workspace_assignments.go, internal/services/domain/resource_domain_workspace_assignments_test.go, internal/services/workspace/resource_workspace_git.go, tools/scripts/Set-WellKnown.ps1
This pull request introduces support for Service Principal (SPN) authentication for various domain-related resources and data sources. The changes span across documentation updates, configuration files, and test cases.
=> feat(domain): enable spn support

.changie.yaml, .semver.yaml, Taskfile.yml
This pull request includes several changes to configuration files and task definitions to improve the release process and streamline tool installations. The most important changes include updating the release preparation process, modifying auto versioning rules, and adding new tasks for installing the GitHub CLI.
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eL362-L390): Enhanced the `release:prep` task to include preconditions for ensuring the user is on the main branch, has a clean working tree, and provides a valid semver format version. Updated the task to use the `VERSION` variable instead of `SEMVER` and included additional commands for creating and merging pull requests.
* …
=> feat: enhance release preparation

.changes/unreleased/breaking-20250310-221022.yaml, docs/data-sources/workspace_role_assignments.md, docs/resources/workspace_role_assignment.md, examples/data-sources/fabric_workspace_role_assignment/data-source.tf, examples/data-sources/fabric_workspace_role_assignment/outputs.tf, examples/data-sources/fabric_workspace_role_assignment/providers.tf, internal/provider/provider.go, internal/services/workspace/base.go, internal/services/workspace/data_workspace_role_assignment.go.dev, internal/services/workspace/data_workspace_role_assignment_test.go.dev, internal/services/workspace/data_workspace_role_assignments.go, internal/services/workspace/data_workspace_role_assignments_test.go, internal/services/workspace/fake_test.go, internal/services/workspace/models_data_workspace_role_assignments.go, internal/services/workspace/resource_workspace_role_assignment.go, internal/services/workspace/resource_workspace_role_assignment_test.go
This pull request introduces updates the principal schema for `fabric_workspace_role_assignments` - naming unification with all resources/data-sources (breaking).
=> feat(ds-workspace_role_assignments)!: update principal schema

Taskfile.yml
This pull request includes a small change to the `Taskfile.yml` file. The change adds a new shell command to check the GitHub CLI authentication status and provides a message if the user is not authenticated.
* [`Taskfile.yml`](diffhunk://#diff-cd2d359855d0301ce190f1ec3b4c572ea690c83747f6df61c9340720e3d2425eR387-R389): Added a shell command to check GitHub CLI authentication status with a corresponding message for unauthenticated users.
=> feat(task): add GitHub CLI authentication check to Taskfile

.vscode/launch.json, .vscode/settings.json, docs/guides/troubleshooting.md, internal/provider/client/logging.go, internal/provider/client/logging_test.go, internal/provider/provider.go, templates/guides/troubleshooting.md
This pull request introduces enhancements to the logging functionality for the Fabric SDK, including the addition of advanced logging options and corresponding documentation updates. The most important changes include the introduction of new environment variables for logging configuration, the implementation of functions to handle these configurations, and the addition of comprehensive tests to ensure the correctness of these new features.
These changes enhance the ability to debug issues by providing more granular control over logging behavior, while ensuring that sensitive information is handled with care.
=> refactor(logging): move to client package package

tools/scripts/Set-WellKnown.ps1
* [`tools/scripts/Set-WellKnown.ps1`](diffhunk://#diff-cd040f9d9e24e510ff0d29df8f78489fbd234634352aa2fbbf2b99a9a52fcc4cL837-R837): Modified the payload definition for `mirroring.json` to use the `.tmpl` file and added values for `DEFAULT_SCHEMA`.
=> fix(wellknown): mirroring tmpl path and add values

internal/services/workspacera/resource_workspace_role_assignment.go
This pull request involves the removal of the mutex lock.
=> refactor: remove unnecessary locks

.changes/unreleased/fixed-20250327-115730.yaml, .github/workflows/test.yml, internal/pkg/fabricitem/resource_item_config_definition_properties.go, internal/pkg/fabricitem/resource_item_config_properties.go, internal/pkg/fabricitem/resource_item_definition_properties.go, internal/pkg/fabricitem/resource_item_properties.go, internal/services/domain/resource_domain.go, internal/services/gateway/resource_gateway.go, internal/services/gatewayra/resource_gateway_role_assignment.go, internal/services/sparkenvsettings/resource_spark_environment_settings.go, internal/services/sparkwssettings/resource_spark_workspace_settings.go, internal/services/workspacera/resource_workspace_role_assignment.go
=> fix: state not properly refreshed

internal/services/gateway/schema.go, tools/scripts/Set-WellKnown.ps1
Update well known pwsh script to add missing role assignments to SPNs security group.
=> fix(wellknown): add missing role assignments to SPNs SG

tools/scripts/Set-WellKnown.ps1
Resource Provider for Microsoft.PowerPlatform and Microsoft.DataFactory are only created if they are not already registered.
=> fix(set_wellknown): updated resource provider to only create it once

.github/ISSUE_TEMPLATE/tfprovider_ephemeral_resource_request.yml
Add new issue template for ephemeral resources
=> feat(issue_template): add ephemeral resource issue template

.devcontainer/devcontainer.json, DEVELOPER.md, go.mod, internal/services/kqldatabase/schema_resource_kql_database.go
This pull request updates the Go version across the project to `1.24.3` and makes a minor version update for the OpenTofu feature in the development container configuration. These changes ensure consistency and compatibility with the latest versions of the tools being used.
=> build: bump go and tofu

.devcontainer/devcontainer.json, .github/workflows/test.yml, .gitignore, DEVELOPER.md, internal/provider/provider.go, internal/services/copyjob/resource_copy_job_test.go, internal/services/gatewayra/data_gateway_role_assignment_test.go, internal/services/workspacegit/resource_workspace_git_test.go, tools/scripts/Set-WellKnown.ps1
- use tf 1.12
- refactor test CI for better clarity
- enable merge queue for PR velocity
- test Copy Job using SPN
- refactor set-wellknown to makes sure it always uses own resource group
- add github connection to wellknown
- add additional gatekeepers for various auth methods
=> build(deps): update terraform 1.12.0

tools/scripts/Set-WellKnown.ps1
Added Deployment Pipeline to WellKnown
=> feat(wellknown): add deployment pipeline

docs/data-sources/environments.md, docs/data-sources/eventhouses.md, docs/data-sources/kql_databases.md, docs/data-sources/lakehouses.md, docs/data-sources/mirrored_databases.md, docs/data-sources/spark_job_definitions.md, docs/data-sources/sql_databases.md, docs/data-sources/warehouses.md, internal/pkg/fabricitem/data_items_properties.go
…tify plural
Fix issue in generating docs to correctly identify plural cases
=> fix(items_properties): correctly identify plural

.changes/unreleased/changed-20250529-091400.yaml, .changes/unreleased/changed-20250529-094238.yaml, docs/data-sources/gateway.md, docs/data-sources/gateway_role_assignment.md, docs/data-sources/gateway_role_assignments.md, docs/data-sources/gateways.md, docs/resources/gateway.md, docs/resources/gateway_role_assignment.md, internal/services/gateway/base.go, internal/services/gatewayra/base.go
Removed preview for `fabric_gateway`. This PR closes #471 and #472
=> feat(gateway): remove preview for Gateway

internal/testhelp/fixtures/digital_twin_builder/definition.json.tmpl, tools/scripts/Set-WellKnown.ps1
Add support for Digital Twin Builder
=> feat(wellknown): add support for digital twin builder

.devcontainer/devcontainer.json, DEVELOPER.md, go.mod
=> build: bump go version

.golangci.yml, internal/auth/oidc.go, internal/auth/utils_test.go, internal/common/warnings.go, internal/framework/customtypes/uuid_value.go, internal/framework/typeutils/dynamic_json.go, internal/functions/content_decode.go, internal/pkg/transforms/payload.go, internal/pkg/transforms/transforms.go, internal/pkg/utils/errors.go, internal/pkg/utils/errors_test.go, internal/pkg/utils/utils.go, internal/provider/client/logging.go, internal/testhelp/fakes/fake_handlers.go
=> feat(lint): new linting rules - noinlineerr

docs/data-sources/shortcut.md, docs/data-sources/shortcuts.md, docs/resources/shortcut.md, examples/data-sources/fabric_shortcut/data-source.tf, examples/data-sources/fabric_shortcut/outputs.tf, examples/data-sources/fabric_shortcuts/data-source.tf, examples/data-sources/fabric_shortcuts/outputs.tf, examples/resources/fabric_shortcut/import.sh, examples/resources/fabric_shortcut/outputs.tf, examples/resources/fabric_shortcut/resource.tf, internal/services/shortcut/resource_shortcut.go
- fix onelake shortcut examples
fix https://github.com/microsoft/terraform-provider-fabric/issues/422#issuecomment-3032019592
close #529
=> feat(fix): onelake shortcut examples

tools/scripts/Set-WellKnown.ps1
Add support for Folder - Subfolders creation
=> feat(wellknown): add support for folder

.github/workflows/test.yml
require for: https://github.com/microsoft/terraform-provider-fabric/pull/580
=> ci(test): run test on push

.devcontainer/devcontainer.json, .github/workflows/test.yml, .vscode/settings.json, internal/services/activator/data_activator_test.go, internal/services/activator/resource_activator_test.go, internal/services/eventstreamsourceconnection/data_evenstream_source_connection_test.go
- test: temporarily skip tests due to SPN auth issue
- bump terraform to the latest: 1.13
=> test: temp skip tests due to SPN auth issue

tools/scripts/Set-WellKnown.ps1
Add support for connection role assignment in wellknown script
=> feat(wellknown): add connection role assignment support

internal/services/activator/data_activator_test.go, internal/services/activator/resource_activator_test.go
Reenable resource and data source activator tests that were previously skipped
=> fix(activator): reenable activator acc tests

internal/services/workspacegit/resource_workspace_git_test.go
=> fix(test): disable workspace_git GitHub acc test

docs/guides/getting_started.md, templates/guides/getting_started.md.tmpl
=> fix(docs): replace getting-started broken link

.github/workflows/test.yml, internal/pkg/fabricitem/helpers.go, internal/pkg/utils/errors.go, internal/services/apacheairflowjob/base.go, internal/services/deploymentpipeline/fake_test.go, internal/services/deploymentpipelinera/fake_test.go, internal/services/domainwa/data_domain_workspace_assignments_test.go, internal/services/eventstreamsourceconnection/fake_test.go, internal/services/gatewayra/fake_test.go, internal/services/lakehousetable/fake_test.go, internal/services/shortcut/fake_test.go, internal/services/shortcut/resource_shortcut_test.go, internal/services/shortcut/schema.go, internal/services/workspace/data_workspace.go, internal/services/workspacegit/fake_test.go, internal/services/workspacegit/resource_workspace_git_test.go, internal/services/workspacera/fake_test.go, internal/testhelp/fakes/fabric_connection.go, internal/testhelp/testacc.go, internal/testhelp/testunit.go, internal/testhelp/utils.go
- codebase lint to meet a new golangci-lint rules
- re-enable GH test
- extend timeout to 40 minutes
=> chore: codebase maintenance
